### ISSUE TITLE
PDB parser cannot handle multi-line REVDAT w/ missing modtype

### ISSUE THREAD

**Issue by dakami** [Electrostatics/pdb2pqr#114]
1E7G has:

```
REVDAT   3   08-JAN-14 1E7G    1       HEADER TITLE  SOURCE KEYWDS              
REVDAT   3 2                           REMARK VERSN  HETSYN FORMUL              
REVDAT   2   24-FEB-09 1E7G    1       VERSN                                    
REVDAT   1   06-NOV-00 1E7G    0   
```
This crashes on:

`self.mod_type = int(line[31].strip())`

The REVDAT parser assumes that mod_type is always present, which it probably has to be, but I guess not always on every line of a multi-line entry?

I just added a simple check to see if the line length is anything after stripping:

`if len(line[31].strip()): self.mod_type = int(line[31].strip())`

But that fix assumes mod_type<10, since there's only a single character.  Unsure if something more general is needed, especially since there's potential elsewhere for destructive parsing bugs (turning a 19 into a 1 or a 9, for instance).

**Comment by sobolevnrm** [comment]
Yes; I need to fix this.  I hope to do so this weekend, if possible.  Thank you.

**Comment by sobolevnrm** [comment]
@dakami -- thanks for creating this issue.  I've added a test that reproduces the problem.  I think your fix is reasonable because the PDB format specification indicates that the mod_type has to be a single digit:  https://www.wwpdb.org/documentation/file-format-content/format33/sect2.html#REVDAT

I'll implement something similar to your fix.

Thanks again.
