### ISSUE TITLE
Failed - Loading Job Data: Out of memory error

### ISSUE THREAD

**Issue by tomcastigl** [Electrostatics/pdb2pqr#188]
Hello,

I try to convert a pdb file I got from charmm-gui webserver into pqr file. I get the error "Failed - Loading Job Data: Out of memory error", is this a known problem?  I could not find information over the internet. The file is not corrupted, I ran gromacs simulations with it. the job ID: lp5byjx1e6

Thanks for help!
Thomas

**Comment by intendo** [comment]
There were a few problems that we found. 
- The VM on our existing Azure cluster was too small to hold all the output data. 
- One of the output files was the standard error log file from pdb2pqr trying to parse the step5_assembly.pdb file. 
- The PDB file has 302,274 ATOMs in it and pdb2pqr can only recognize the first 99,999 because the PDB file format does not support more than 99,999 ATOMs/HETATMs.

You can try to run your job again on our [AWS Cluster](https://apbs.labworks.org) that has more memory. We don't know how to help  fix the underlying problem with the large number of ATOMs in the PDB file.

Please let us know if you are able to run your job on the AWS Cluster.

**Comment by tomcastigl** [comment]
It works on the AWS cluster! thank you very much.

**Comment by intendo** [comment]
Thanks @tomcastigl
