### ISSUE TITLE
Error with the online web server

### ISSUE THREAD

**Issue by bb2n18** [Electrostatics/pdb2pqr#191]
Hi,

I use the online web server to get the electrostatic profile of a protein surrounded by many lipids.
I load a pdb file together with a mol2 file for the parameters of the lipids, however it crashes with the following error:

Error parsing line: invalid literal for int() with base 10: 'ori'
<REMARK original generated coordinate pdb file>
Duplicate atom names (N) found in ligand file!
Duplicate atom names (CA) found in ligand file!
Duplicate atom names (HA) found in ligand file!
...

All my lipid atoms present errors since lipids have the same names and atom names. Is there a way to make APBS read the residue IDs instead of the atoms so it understands the correspondance between atoms and ligands please?

Many thanks

**Comment by sobolevnrm** [comment]
@Eo300 @intendo can you please look into this?

**Comment by Eo300** [comment]
Hi @bb2n18, apologies for the issues you're experiencing.  Are you willing to share the PDB/mol2 files or the the ID of the job where you're encountering this?  It should help with the troubleshooting process.  Thanks!

**Comment by bb2n18** [comment]
Hi @Eo300 ,

Thanks for your reply! Sorry for my late one.
Sure, I can share the files I used, and the ID of the online job I just tried is: mnb75dcw9h
How can I send you the files? It seems that these formats are not supported on this chat...

**Comment by sobolevnrm** [comment]
@bb2n18 -- I think you can just add "*.txt" to the end of the PBD/MOL2/input files.

**Comment by bb2n18** [comment]
[frame300_vmd.pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/6576867/frame300_vmd.pdb.txt)
[frame_0.mol2.txt](https://github.com/Electrostatics/pdb2pqr/files/6576873/frame_0.mol2.txt)

**Comment by bb2n18** [comment]
Nice! Thank you @sobolevnrm

**Comment by Eo300** [comment]
**Regarding the error: Error parsing line: invalid literal for int() with base 10: 'ori':**
I noticed the REMARK your PDB file contains some incorrect column spacing.  The REMARK statement expects a record number integer within columns 8 through 10, whereas your remark string follows the "REMARK" keyword.  PDB2PQR attempts to parse the substring "ori" as an integer.
Moving "original" to start at the 12th character and adding an integer where "ori" of "original" currently is should relieve that error (looking at the [format](http://www.wwpdb.org/documentation/file-format-content/format33/remarks.html) should make it clear).
**Example**: 
```
REMARK   1 original generated coordinate pdb file
```
instead of...
```
REMARK original generated coordinate pdb file
```


As for having PDB2PQR read the residue IDs instead of names when associating items in the ligand file, is this something possible today or would it classify as a new feature request, @sobolevnrm / @intendo ?

**Comment by sobolevnrm** [comment]
> As for having PDB2PQR read the residue IDs instead of names when associating items in the ligand file, is this something possible today or would it classify as a new feature request, @sobolevnrm / @intendo ?

I agree that this could be a new feature request but I'm not sure it would get very high priority for a while.  Sorry.

**Comment by bb2n18** [comment]
Hi, thank you for your replies.
I corrected the "REMARK" line. However, I just tried to run the same calculation on the protein with only one lipid as a ligand. And I get the same issue, and I noticed that the error file presents the error as "Duplicate atom names (O) found in ligand file!" for atoms that don't belong to the ligand but to the protein. Should I only have the ligand atoms in the mol2 file that gives the atomic charges?

**Comment by sobolevnrm** [comment]
I don't understand what's going on with the [provided MOL2 file](https://github.com/Electrostatics/pdb2pqr/files/6576873/frame_0.mol2.txt):  it contains several atoms/groups that should be represented as amino acids in a PDB file instead.  Since this appears to be an invalid ligand file, I am closing the issue until the user can provide clarification.
