### ISSUE TITLE
the shell command shouw

### ISSUE THREAD

**Issue by swdoctor** [Electrostatics/pdb2pqr#228]
Dear pdb2pqr  author :

the command line pdb2pqr30 show me give up, but in your website it works right. 

My command is "pdb2pqr30 --titration-state-method=propka --with-ph=6.0 --ff=AMBER --ffout=AMBER ./T3_1u19_0_protein.pdb ./AAA.pqr"

The pdb documents in T3_1u19_0_protein.pdb.txt, you need move T3_1u19_0_protein.pdb.txt to T3_1u19_0_protein.pdb
[T3_1u19_0_protein.pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/7215234/T3_1u19_0_protein.pdb.txt)

**Comment by jbardhan** [comment]
Hi, 

Just to check, this is the error you get from the command line? 

CRITICAL:Residue WAT 964 charge is non-integer: -0.417
CRITICAL:Giving up.


Thanks very much,
Jay

**Comment by jbardhan** [comment]
It *looks* like the use of multiple hydrogens named "HW" in the water residue is the culprit.  The oxygen has a charge of -0.834 and the hydrogens each have +0.417.  

To test this, I took out all the waters but 964, and changed the water hydrogen names to H1 and H2.  After doing this, pdb2pqr30 ran successfully using the command you gave.

I'm a bit confused because the atom name "HW" seems to be appropriate for AMBER.  As a result, I'm not sure why the code would fail on this, nor am I sure why it works on the website but not command line.

@intendo , can you please have a look at this?  I'll keep looking at it as well.

Thanks very much,
Jay

**Comment by jbardhan** [comment]
I am unable to get this working on the website either ( https://server.poissonboltzmann.org/ ) .  Can you please share the jobID that succeeded, and ideally the date you submitted the job as well?

Thanks very much,
Jay

**Comment by sobolevnrm** [comment]
There appears to be something wrong with the water molecules in this file.  When I delete them, the problem goes away.

**Comment by sobolevnrm** [comment]
And the problem appears to be with the water hydrogens -- when I delete the hydrogens the run also completes without problem.

**Comment by sobolevnrm** [comment]
> It _looks_ like the use of multiple hydrogens named "HW" in the water residue is the culprit. The oxygen has a charge of -0.834 and the hydrogens each have +0.417.
> 
> To test this, I took out all the waters but 964, and changed the water hydrogen names to H1 and H2. After doing this, pdb2pqr30 ran successfully using the command you gave.
> 
> I'm a bit confused because the atom name "HW" seems to be appropriate for AMBER. As a result, I'm not sure why the code would fail on this, nor am I sure why it works on the website but not command line.
> 
> @intendo , can you please have a look at this? I'll keep looking at it as well.
> 
> Thanks very much, Jay

I've confirmed what @jbardhan mentioned above:  the duplicate water hydrogen names are causing the problem.  The attached version of the PDB works with PDB2PQR:  [T3_1u19_0_protein-fixed.pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/7794634/T3_1u19_0_protein-fixed.pdb.txt)
