### ISSUE TITLE
server stuck

### ISSUE THREAD

**Issue by sunimei3** [Electrostatics/pdb2pqr#318]
Hi 
Is PDB2PQR server stuck or just the queue is very long suddenly?

**Comment by sobolevnrm** [comment]
Hello.  I just tried a calculation and it worked without issue.  Can you please try again and/or post more information about the specific calculation that failed for you?

**Comment by sunimei3** [comment]
https://server.poissonboltzmann.org/jobstatus?jobtype=pdb2pqr&jobid=k9pf3zbqi6&date=2022-05-26

**Comment by sunimei3** [comment]
https://server.poissonboltzmann.org/jobstatus?jobtype=pdb2pqr&jobid=tdw0m9u72g&date=2022-05-27

**Comment by sunimei3** [comment]
I see, it seems to be input-dependent. It hangs there if I use a certain input. I will look at the file I submited

**Comment by sunimei3** [comment]
https://server.poissonboltzmann.org/jobstatus?jobtype=pdb2pqr&jobid=edfrkmxem7&date=2022-05-27

**Comment by sobolevnrm** [comment]
There is a problem with the charge assignment routine on your input file.  Does it have unusual atoms in it?

**Comment by GeorgianaLiang** [comment]
Is there any specific way to tweak the input to enable the job to run faster (with shorter pending time)?

**Comment by jbardhan** [comment]
Hello!

Is this last question (about enabling the job to run faster) about the same inputs/problems used in the original question that opened this issue?  Just checking if we should open a new ticket.

Thanks,
Jay

**Comment by GeorgianaLiang** [comment]
Thank you so much for the email!
The problem was solved.
Thanks,
Georgiana

发件人: Jaydeep Bardhan ***@***.***>
发送时间: 2022年6月24日 16:24
收件人: Electrostatics/pdb2pqr ***@***.***>
抄送: GeorgianaLiang ***@***.***>; Comment ***@***.***>
主题: Re: [Electrostatics/pdb2pqr] server stuck (Issue #318)


Hello!

Is this last question (about enabling the job to run faster) about the same inputs/problems used in the original question that opened this issue? Just checking if we should open a new ticket.

Thanks,
Jay
