### ISSUE TITLE
Add code warnings and documentation about the --keep-protons option being ignored

### ISSUE THREAD

**Issue by dargen3** [Electrostatics/pdb2pqr#365]
Hello,

I'd like to report a potential bug. I protonated the structure with 
`pdb2pqr30 --noopt --nodebump --keep-protons --pdb-output repaired_substructure.pdb substructure.pdb repaired_substructure.pqr`
Although I used --keep-protons flag hydrogen ATOM 223 HE2 HIS A 32 4.906 8.213 6.758 1.00 0.00 H is missing from the repaired_substructure.pdb file. I used pdb2pqr 3.6.1.

[files.zip](https://github.com/Electrostatics/pdb2pqr/files/11879984/files.zip)

**Comment by sobolevnrm** [comment]
Hello --

The `--keep-protons` flag is a [PROPKA](https://github.com/jensengroup/propka) option, one of the libraries PDB2PQR uses.  We provide access to the PROPKA options by popular request; however, this sometimes creates confusion when PDB2PQR overrides the PROPKA behavior.  Since PDB2PQR optimizes and sometimes replaces hydrogens based on the predicted pKa and given pH, it ignores the `--keep-protons` keyword.  I should update the documentation and/or the code to clarify this point.  However, it only be a change to the documentation and will not follow the PROPKA behavior.

Thank you,

Nathan
